# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Moshdrop < Formula
  desc "Keep mosh. Just drop files. Drag-and-drop file upload for mosh sessions."
  homepage "https://github.com/rrrrrrrrrricoxi/moshdrop"
  version "1.0.1"
  license "MIT"

  depends_on "mosh"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/rrrrrrrrrricoxi/moshdrop/releases/download/v1.0.1/moshdrop_1.0.1_darwin_amd64.tar.gz"
    sha256 "de787a9dcc33fcfa71c426a239270d05a6913b549147d27ea5be475e9f4546e7"

    define_method(:install) do
      bin.install "moshdrop"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/rrrrrrrrrricoxi/moshdrop/releases/download/v1.0.1/moshdrop_1.0.1_darwin_arm64.tar.gz"
    sha256 "01f5db2222f66f16872ad1eae063329a479cffb206bfcf4d462c0635395c8443"

    define_method(:install) do
      bin.install "moshdrop"
    end
  end
end
